## Homepage microservice configuration

# Application name
spring:
  application:
    name: homepage

# Tomcat configuration
server:
  port: 9080

# Discovery service configuration
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.99.100:8761/eureka/ # VM address
